include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    avoid_empty_else: true
    prefer_single_quotes: true
    always_declare_return_types: true
    annotate_overrides: true
    sort_child_properties_last: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: false
    empty_constructor_bodies: true
    always_put_required_named_parameters_first: true
